replicaCount: 1

image:
  repository: harness-lemmings
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 31991

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

namespace: lemmings
