[sdl]
fullscreen=false
output=surface

[mixer]
rate=44100
blocksize=1024
prebuffer=20

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default
oplrate=44100

[autoexec]
mount c .
c:
vgalemmi.exe
